const SITEMAP = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>https://multiportgames.pages.dev/</loc><lastmod>2026-07-02</lastmod><changefreq>weekly</changefreq><priority>1.0</priority></url>
  <url><loc>https://multiportgames.pages.dev/privacy.html</loc><lastmod>2026-06-07</lastmod><changefreq>yearly</changefreq><priority>0.3</priority></url>
  <url><loc>https://multiportgames.pages.dev/terms.html</loc><lastmod>2026-06-07</lastmod><changefreq>yearly</changefreq><priority>0.3</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/2048.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/airhockey.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/anagram.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/archery.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/asteroids.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/ballbounce.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/ballpit.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/baseball.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/basketball.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/battleship.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/bingo.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/birdfly.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/blackjack.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/blockslide.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/bowling.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/breakout.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/brickroad.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/bubble.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/candy.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/cannon.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/catching.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/checkers.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/chess.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/clicker.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/colorflood.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/connect4.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/crossword.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/crossy.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/curling.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/darts.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/dino.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/dodge.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/dominoes.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/dotsboxes.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/fifteenpuzzle.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/fishing.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/flags.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/flappy.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/flappydunk.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/geometry.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/gravity.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/hangman.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/hovercraft.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/icebreak.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/jetpack.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/jigsaw.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/jumper.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/knifecut.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/lander.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/level67.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/lightcycle.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/mancala.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/mathblast.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/maze.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/memetash.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/memory.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/minesweeper.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/minigolf.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/nim.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/nonogram.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/numguess.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/pacmaze.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/pianotiles.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/pinball.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/platformer.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/plinko.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/pong.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/racer.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/reaction.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/reversi.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/rps.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/sasquatch.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/scramble.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/shooter.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/simon.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/skyrace.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/slingshot.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/slots.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/snake.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/soccer.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/solitaire.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/spaceinvaders.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/spelling.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/stackfall.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/strands.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/sudoku.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/swords.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/tetris.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/tictactoe.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/timestable.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/towerdefense.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/trivia.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/typing.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/videopoker.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/whackamole.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/wordjump.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/wordladder.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/wordle.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/wordsearch.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
  <url><loc>https://multiportgames.pages.dev/games/yahtzee.html</loc><lastmod>2026-07-02</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>
</urlset>`;

export async function onRequestGet() {
  return new Response(SITEMAP, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
}
